create type public.app_role as enum ('member', 'organizer', 'admin');
create type public.profile_status as enum ('pending', 'active', 'suspended');

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  member_number bigint generated by default as identity (start with 1001),
  first_name text not null default '',
  last_name text not null default '',
  grade smallint check (grade between 7 and 12),
  direction text check (direction in ('Machine Learning', 'Arduino', 'Both', 'Not sure')),
  level text check (level in ('Beginner', 'Intermediate', 'Advanced')),
  skills text[] not null default '{}',
  competition_interest boolean not null default false,
  role public.app_role not null default 'member',
  status public.profile_status not null default 'pending',
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_member_number_unique unique (member_number)
);

create table public.member_contacts (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  email text not null,
  whatsapp text not null default '',
  updated_at timestamptz not null default now()
);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  location text not null,
  description text not null default '',
  attendee_count integer not null default 0 check (attendee_count >= 0),
  status text not null default 'upcoming' check (status in ('upcoming', 'past', 'cancelled')),
  category text not null default 'Club event',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint events_time_order check (ends_at > starts_at)
);

create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  published_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.event_rsvps (
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

create index profiles_status_idx on public.profiles(status);
create index profiles_role_idx on public.profiles(role);
create index events_starts_at_idx on public.events(starts_at);
create index announcements_published_at_idx on public.announcements(published_at desc);
create index event_rsvps_user_id_idx on public.event_rsvps(user_id);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public, anon, authenticated;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger contacts_set_updated_at
before update on public.member_contacts
for each row execute function private.set_updated_at();

create trigger events_set_updated_at
before update on public.events
for each row execute function private.set_updated_at();

create trigger announcements_set_updated_at
before update on public.announcements
for each row execute function private.set_updated_at();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  display_name text;
  given_name text;
  family_name text;
  initial_role public.app_role;
  initial_status public.profile_status;
begin
  display_name := coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', '');
  given_name := coalesce(nullif(new.raw_user_meta_data ->> 'given_name', ''), split_part(display_name, ' ', 1), '');
  family_name := coalesce(
    nullif(new.raw_user_meta_data ->> 'family_name', ''),
    nullif(trim(substring(display_name from length(split_part(display_name, ' ', 1)) + 1)), ''),
    ''
  );

  if lower(coalesce(new.email, '')) = 'yertay.yera55@gmail.com' then
    initial_role := 'admin';
    initial_status := 'active';
  else
    initial_role := 'member';
    initial_status := 'pending';
  end if;

  insert into public.profiles (id, first_name, last_name, role, status)
  values (new.id, given_name, family_name, initial_role, initial_status)
  on conflict (id) do nothing;

  insert into public.member_contacts (user_id, email)
  values (new.id, coalesce(new.email, ''))
  on conflict (user_id) do update set email = excluded.email;

  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;

create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function private.handle_new_user();

-- Backfill real Auth users if the project already had a login before this migration.
insert into public.profiles (id, first_name, last_name, role, status)
select
  users.id,
  coalesce(nullif(users.raw_user_meta_data ->> 'given_name', ''), split_part(coalesce(users.raw_user_meta_data ->> 'full_name', ''), ' ', 1), ''),
  coalesce(nullif(users.raw_user_meta_data ->> 'family_name', ''), ''),
  case when lower(coalesce(users.email, '')) = 'yertay.yera55@gmail.com' then 'admin'::public.app_role else 'member'::public.app_role end,
  case when lower(coalesce(users.email, '')) = 'yertay.yera55@gmail.com' then 'active'::public.profile_status else 'pending'::public.profile_status end
from auth.users as users
on conflict (id) do nothing;

insert into public.member_contacts (user_id, email)
select users.id, coalesce(users.email, '')
from auth.users as users
on conflict (user_id) do update set email = excluded.email;

create or replace function private.is_active_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid()) and status = 'active'
  );
$$;

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and status = 'active'
      and role in ('organizer', 'admin')
  );
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and status = 'active'
      and role = 'admin'
  );
$$;

revoke all on function private.is_active_member() from public, anon;
revoke all on function private.is_staff() from public, anon;
revoke all on function private.is_admin() from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.is_active_member() to authenticated;
grant execute on function private.is_staff() to authenticated;
grant execute on function private.is_admin() to authenticated;

create or replace function private.refresh_event_attendee_count()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_event_id uuid;
begin
  target_event_id := coalesce(new.event_id, old.event_id);
  update public.events
  set attendee_count = (
    select count(*)::integer
    from public.event_rsvps
    where event_id = target_event_id
  )
  where id = target_event_id;
  return coalesce(new, old);
end;
$$;

revoke all on function private.refresh_event_attendee_count() from public, anon, authenticated;

create trigger event_rsvps_refresh_count
after insert or delete on public.event_rsvps
for each row execute function private.refresh_event_attendee_count();

alter table public.profiles enable row level security;
alter table public.member_contacts enable row level security;
alter table public.events enable row level security;
alter table public.announcements enable row level security;
alter table public.event_rsvps enable row level security;

revoke all on public.profiles from anon, authenticated;
revoke all on public.member_contacts from anon, authenticated;
revoke all on public.events from anon, authenticated;
revoke all on public.announcements from anon, authenticated;
revoke all on public.event_rsvps from anon, authenticated;

grant select on public.profiles to authenticated;
grant update (first_name, last_name, grade, direction, level, skills, competition_interest, bio) on public.profiles to authenticated;
grant select on public.member_contacts to authenticated;
grant update (email, whatsapp) on public.member_contacts to authenticated;
grant select, insert, update, delete on public.events to authenticated;
grant select, insert, update, delete on public.announcements to authenticated;
grant select, insert, delete on public.event_rsvps to authenticated;

create policy "profiles_select_authorized"
on public.profiles for select
to authenticated
using (
  id = (select auth.uid())
  or (status = 'active' and (select private.is_active_member()))
  or (select private.is_admin())
);

create policy "profiles_update_self"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy "contacts_select_authorized"
on public.member_contacts for select
to authenticated
using (user_id = (select auth.uid()) or (select private.is_staff()));

create policy "contacts_update_self"
on public.member_contacts for update
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create policy "events_select_active_members"
on public.events for select
to authenticated
using ((select private.is_active_member()));

create policy "events_insert_staff"
on public.events for insert
to authenticated
with check ((select private.is_staff()) and created_by = (select auth.uid()));

create policy "events_update_staff"
on public.events for update
to authenticated
using ((select private.is_staff()))
with check ((select private.is_staff()));

create policy "events_delete_staff"
on public.events for delete
to authenticated
using ((select private.is_staff()));

create policy "announcements_select_active_members"
on public.announcements for select
to authenticated
using ((select private.is_active_member()));

create policy "announcements_insert_staff"
on public.announcements for insert
to authenticated
with check ((select private.is_staff()) and created_by = (select auth.uid()));

create policy "announcements_update_staff"
on public.announcements for update
to authenticated
using ((select private.is_staff()))
with check ((select private.is_staff()));

create policy "announcements_delete_staff"
on public.announcements for delete
to authenticated
using ((select private.is_staff()));

create policy "rsvps_select_authorized"
on public.event_rsvps for select
to authenticated
using (user_id = (select auth.uid()) or (select private.is_staff()));

create policy "rsvps_insert_self"
on public.event_rsvps for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and (select private.is_active_member())
);

create policy "rsvps_delete_self"
on public.event_rsvps for delete
to authenticated
using (user_id = (select auth.uid()));
